### ISSUE TITLE
Suspect Data Repeat (MBAFC)

### ISSUE THREAD

**Issue by Daimler666** [Daimler666/Data-Lake-Ticket-Platform#11]

**Comment by Daimler666** [comment]
**_/Raised by Felix Liu/_**

**Issue:**
1.  One record repeat in data lake table 30 times, but there is only one record in source. Please arrange to check it.

**Comment by madhushanmugam** [comment]
We have fixed this issue. Validate and take it to closure.

**Comment by Daimler666** [comment]
_**/Closed by Derek/**_

Have been cheked.
