### ISSUE TITLE
Data Correctness Verification (DMS)

### ISSUE THREAD

**Issue by Daimler666** [Daimler666/Data-Lake-Ticket-Platform#9]

**Comment by Daimler666** [comment]
**_/Raised by Liu Jun/_**

**Issues Summary:**

The data in our lake is NOT complete set comopare with original data source which introduce some trust risk.

**Status(ASAP NEED/CASE):**
1. MBAFC escalate our salesforce dealer data is NOT complete, sf data source has ~460 dealer items,  but DL only have ~300. (please verify the data correctness ASAP);
2. AS team would like use DL DMS data, but they wanna compare our data with DMS source first. The data they wanna compare is,
    Target Customer Segmentation Criteria
    1)	Age: 2.7 ~ 3 Years based on reporting date and first registration date 
    2)	Service history: 6 months not into workshop

**Comment by Daimler666** [comment]
**_/Replied by Felix Liu/_**

**Status:**
1. There is still some records we cannot update (details can be seen from email);

**Sugesstions:**
1. According to SFDC Source team, every morning at 1 AM , they begin to do the update for dealer info as BU required. During their update, when we do the extract process we may lost something;
2. Lastmodifieddate column is a timpstamp format. So we can use that to limit more accurate time slot;
3. They do not suggest us  to do update during 0:00AM to 2:00AM while they may doing some data process;
4. The worked test sql and query sql (about time setting) have been provided via email.

**Task:**
1. Need someone to share opinion and solve the issues;
2. Need to push the dealer data again on every Friday.

**Comment by Daimler666** [comment]
**_/Replied by Madhu/_**

**Issues:**
1. For Case 2, cannot identify the dms table name and map it with "Target Customer Segmentation‘’.

**Comment by Daimler666** [comment]
**_/Replied by Felix Liu/_**

**Status:**
1. Only sql and result data have been provided by clients.

**Comment by Daimler666** [comment]
**_/Replied by Felix Liu/_**

**Issues:**
1. BU clients asked for the result of this matter and I have not receive any reply or status feedback.

**Task:**
1. Feedback for the changes and data load issues;
2. Further request for data quality checking incoming.

**Comment by Daimler666** [comment]
**_/Replied by Madhu/_**

**Status:**
1. Have problem with 2 tables (SO_HEADR, VS_NEWST) and the shared client’s query is on other 3 different tables. So the data quality should be good.

**Comment by Daimler666** [comment]
**_/Replied by Felix Liu/_**

**Status:**
1. After checking, there is a server data quality issue.

**Issues (ASAP REQUIRED):**

The problem **table is dw_dealer_dms_srvc_so_logla**;\
1. The data lake is around **93653863**, but in source system, this table only have **35383543** rows;
2. There a column called WIP_NO in this table, in our data lake table, **it’s only one value “0”**, but in source system, there’s obvious **meaningful value in this column.**

**Task:**
1. Check the data quality and incremental logic for this table and find out reasons ASAP.

**Comment by Daimler666** [comment]
**_/Replied by Madhu/_**

**Status:**
1. Since there are both Chinese and English characters, the higher row count exit in data lake;
2. We do not want to stick to the process of extracting raw data but to focus on issues during the process extracting data to files;
3. We have plans to modify and we can do it according to priority tables.

**Comment by Daimler666** [comment]
**_/Replied by Felix Liu/_**

**Here are some priority tables:**

dw_dealer_dms_srvc_cscn_histy
dw_vhcl_dms_sles_mk_vehic
dw_dealer_dms_srvc_cscn_hisdt
dw_dealer_dms_srvc_so_logla
DW_DEALER_DMS_SRVC_WL_XVAIL
DW_DEALER_DMS_SRVC_SO_LOGHD

**Comment by Daimler666** [comment]
**_/Replied by Felix Liu/_**

**Remind:**

How’s the DMS data quality check? Any result for now?

**Comment by Daimler666** [comment]
**_/Replied by Debdatta/_**

**Status:**
1. All priority 6 tables completed;
2. Team is working on other tables, and timelines of completion will be provided.

**Comment by Daimler666** [comment]
**_/Replied by Madhu/_**

**Status:**
1. In the total 54 tables, almost done with 40+ tables and we are expected to complete the rest by tomorrow EOD.

**Comment by Daimler666** [comment]
**_/Replied by Madhu/_**

**Status:**
1. We are done with 53 tables and only left with "dw_dealer_dms_srvc_wl_calnd" table;
2. All unnecessary tables and folders have been deleted;
3. In "dw_dealer_dms_srvc_wl_calnd" table, we have close 700+ columns in that table and we are facing heap size memory issue and we are investigating whether it is fine under our environment.

**Comment by madhushanmugam** [comment]
We are done with dw_dealer_dms_srvc_wl_calnd and data is populated. Pls validate and take it to closure.

**Comment by Daimler666** [comment]
**_/Closed by Derek/_**

Have been checked.
